---
deployment:
tasks:
- export DEPLOYPATH=/home/lennartcp/repositories/test
- /bin/cp -R public $DEPLOYPATH
- /bin/cp index.js $DEPLOYPATH
- /bin/cp package.json $DEPLOYPATH
- /bin/cp package-lock.json $DEPLOYPATH
- /bin/cp .cpanel.yml $DEPLOYPATH





